export const regionsArray = [
  { label: "UAE", value: "UAE" },
  { label: "France", value: "France" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Belgium", value: "Belgium" },
  { label: "Germany", value: "Germany" },
  { label: "Austria", value: "Austria" },
  { label: "Spain", value: "Spain" },
  { label: "Italy", value: "Italy" },
  { label: "Portugal", value: "Portugal" },
  { label: "Finland", value: "Finland" },
  { label: "Sweden", value: "Sweden" },
  { label: "Poland", value: "Poland" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Denmark", value: "Denmark" },
  { label: "Ireland", value: "Ireland" },
  { label: "Romania", value: "Romania" },
  { label: "Slovakia", value: "Slovakia" },
  { label: "Czech Republic", value: "Czech Republic" },
  { label: "Greece", value: "Greece" },
  { label: "Hungary", value: "Hungary" },
];
